language: python
python:
    - "2.7"

install:
  - pip install -r external_requirements.txt
  - pip install -r test_requirements.txt
  - pip install "cloudshell-automation-api>=9.0.0.0,<9.0.1.0" --extra-index-url https://test.pypi.org/simple
  - pip install "cloudshell-cp-core" --extra-index-url https://test.pypi.org/simple
  - bash ./install_dependencies.sh

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls
    

