language: python
python:
    - "2.7"

install:
  - pip install -r external_requirements.txt
  - pip install -r test_requirements.txt
  - bash ./install_dependencies.sh

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls
    

